language: ruby
rvm:
  - "2.2.1"
env:
  - DB=postgresql
script:
  - export RAILS_ENV=test
  - bundle exec rake db:migrate --trace
  - bundle exec rspec
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database lk_lunch_test' -U postgres
