default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: lk_lunch_<%= Rails.env %>

development:
  <<: *default
  username: 'postgres'
  password:

test:
  <<: *default
  username: 'postgres'
  password:

production:
  <<: *default
  username: lk_lunch
  password: <%= ENV['LK_LUNCH_DATABASE_PASSWORD'] %>
